config:
  default: true
  MD012: false
  MD013: false
  MD022: false
  MD024: false
  MD032: false
  MD033: false
  MD034: false
  MD036: false
  MD040: false
  MD041: false
  MD051: false
  MD055: false
  MD056: false
ignores:
  - .agent/**
  - .agents/**
  - .claude/**
