#!/bin/bash
# Applies a list of patches from Jules and creates Pull Requests.
# Safe mode: uses isolated git worktrees, avoids destructive checkout/reset in the main workspace.
set -euo pipefail

# [FILL: Add Jules session IDs to process. Retrieve them via: bash .agent/scripts/jules-api.sh list-sessions]
# Example:
IDS=(
    # 12345678901234567890
    # 98765432109876543210
)

DEFAULT_BRANCH="$(git symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')"
DEFAULT_BRANCH="${DEFAULT_BRANCH:-master}"

for id in "${IDS[@]}"; do
    echo "=================================================="
    echo "🚀 Processing session $id..."

    if [[ ! "$id" =~ ^[0-9]+$ ]]; then
        echo "⚠️  Invalid session ID format: $id. Skipping."
        continue
    fi

    PATCH_FILE=".agent/tmp/${id}.patch"
    MSG_FILE=".agent/tmp/${id}_msg.txt"

    if [[ ! -f "$PATCH_FILE" ]]; then
        echo "⚠️  Patch file not found for $id. Skipping."
        continue
    fi

    BRANCH_NAME="test-jules-${id}"
    WORKTREE_DIR=".agent/tmp/worktree-${id}"

    rm -rf "$WORKTREE_DIR"
    git worktree add -B "$BRANCH_NAME" "$WORKTREE_DIR" "origin/$DEFAULT_BRANCH" -q

    (
        cd "$WORKTREE_DIR"

        if git apply --3way "../${id}.patch"; then
            echo "✅ Patch applied successfully."
            RAW_TITLE="$(head -n 1 "../${id}_msg.txt" 2>/dev/null || echo "Jules session ${id}")"
            CLEAN_TITLE="$(echo "$RAW_TITLE" | sed 's/^[[:upper:]]/\L&/')"
            COMMIT_TITLE="test(jules): $CLEAN_TITLE"

            git add -A
            if git diff --cached --quiet; then
                echo "ℹ️  No staged changes after applying patch. Skipping commit."
                exit 0
            fi

            git commit -m "$COMMIT_TITLE" -m "$(cat "../${id}_msg.txt" 2>/dev/null || echo "Jules session ${id}")" -q

            echo "⬆️ Pushing branch to remote..."
            git push -u origin "$BRANCH_NAME" -q

            echo "🌟 Creating Pull Request..."
            gh pr create \
                --title "🧪 $COMMIT_TITLE" \
                --body "This PR contains automated testing improvements generated by Jules for session [$id](https://jules.google.com/task/$id)." \
                --head "$BRANCH_NAME" \
                --base "$DEFAULT_BRANCH" || echo "⚠️ PR creation might have failed."
        else
            echo "❌ Failed to apply patch for $id. Skipping."
        fi
    )

    git worktree remove "$WORKTREE_DIR" --force
done

echo "🎉 Finished processing PRs."
