#!/usr/bin/env python3
"""Generate (or verify freshness of) the template health report at docs/TEMPLATE-HEALTH.md.

Usage:
  python3 scripts/template-health-report.py           # write/refresh the report
  python3 scripts/template-health-report.py --check   # exit non-zero if report is stale
"""
from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "TEMPLATE-HEALTH.md"


def glob_files(pattern: str) -> int:
    """Count files matching a glob pattern under ROOT.

    Uses pathlib.rglob so no external tools are needed. The pattern must be of
    the form ``<dir>/<rest>`` where ``<dir>`` is a top-level directory and
    ``<rest>`` is a glob suffix such as ``skills/**/SKILL.md``.
    """
    parts = pattern.split("/", 1)
    base = ROOT / parts[0]
    rest = parts[1] if len(parts) > 1 else "*"
    return sum(1 for p in base.rglob(rest) if p.is_file())


def count_fill_markers() -> tuple[int, int]:
    file_count = 0
    marker_count = 0
    for path in ROOT.rglob("*.md"):
        if ".git" in path.parts:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        c = len(re.findall(r"\[FILL:", text))
        if c:
            file_count += 1
            marker_count += c
    return file_count, marker_count


def render() -> str:
    fill_files, fill_markers = count_fill_markers()
    universal_skills = glob_files(".agents/skills/**/SKILL.md")
    claude_skills = glob_files(".claude/skills/**/SKILL.md")
    agent_skills = glob_files(".agent/skills/**/SKILL.md")
    gha_workflows = glob_files(".github/workflows/*.yml")
    agent_workflows = glob_files(".agent/workflows/*.md")

    return "\n".join(
        [
            "# Template Health Report",
            "",
            "## Snapshot",
            "",
            "| Metric | Value |",
            "| --- | --- |",
            f"| Markdown files containing placeholders | {fill_files} |",
            f"| Total placeholder markers | {fill_markers} |",
            f"| Universal skills (`.agents`) | {universal_skills} |",
            f"| Claude skills (`.claude`) | {claude_skills} |",
            f"| Agent skills (`.agent`) | {agent_skills} |",
            f"| GitHub Actions workflows | {gha_workflows} |",
            f"| Agent workflow playbooks | {agent_workflows} |",
            "",
            "## Notes",
            "",
            "- This report is generated by `scripts/template-health-report.py`.",
            "- Run `python3 scripts/template-health-report.py` to refresh this file.",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if report is outdated")
    args = parser.parse_args()

    try:
        content = render()
    except RuntimeError as exc:
        print(f"[health] ERROR: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"[health] ERROR: filesystem failure: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if not OUT.exists():
            print(f"[health] ERROR: {OUT.relative_to(ROOT)} is missing", file=sys.stderr)
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current != content:
            print(f"[health] ERROR: {OUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        print("[health] OK: template health report is up to date")
        return 0

    OUT.write_text(content, encoding="utf-8")
    print(f"[health] Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
